export * from "@/pages/dashboard/dashboardhome";
export * from "@/pages/dashboard/profile";
export * from "@/pages/dashboard/tables";
export * from "@/pages/dashboard/notifications";
export * from "@/pages/dashboard/paidplans";
export * from "@/pages/dashboard/simulation";
export * from "@/pages/dashboard/moleculeviewer";
export * from "@/pages/dashboard/molecule2d";
export * from "@/pages/dashboard/molstar3d";
